import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import '../globals.css'
import styles from '../page.module.css'
import Header from './components/Header/Header';
import Sidebar from './components/Sidebar/Sidebar';
import Footer from './components/Footer/Footer';

const notoSans = Noto_Sans({
  subsets: ['cyrillic'],
  display: 'swap',
  weight: ['300', '400', '500', '700'], 
});

export const metadata: Metadata = {
  title: 'Наш проект',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ua">
      <body className={notoSans.className}>
        <Header />
        <div>
          <Sidebar />
          <div>{children}</div>
        </div>
        <Footer/>
      </body>
    </html>
  )
}
 