import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import '../globals.css'
import styles from '../page.module.css'

const notoSans = Noto_Sans({
  subsets: ['cyrillic'],
  display: 'swap',
  weight: ['300', '400', '500', '700'], 
});

export const metadata: Metadata = {
  title: 'Наш проект',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ua">
      <body className={notoSans.className}>
        <nav className={styles.nav}>
          <ul>
            <li>Курси</li>
            <li>Для дітей</li>
            <li>Про нас</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
 